name: gitleaks
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7 pinned
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@cb7149b9b57195b609c63a8518d2c37118bbe629  # v2.3.6 pinned
